"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any, Type, TypeGuard, overload

@overload
def dprint[T](args: T) -> T:
    ...

@overload
def dprint[*Tp](*args: *Tp) -> tuple[*Tp]:
    ...

@overload
def is_what[T](obj: Any, dtype: Type[T]) -> TypeGuard[T]:
    ...

@overload
def is_what[T](obj: Any, dtype: type, _stype: Type[T]) -> TypeGuard[T]:
    ...

def only_once[T,**P](func: Callable[P, T]) -> Callable[P, T]:
    ...

def timeof[T,**P](func: Callable[P, T]) -> Callable[P, T]:
    ...
