"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import overload

@overload
def dprint[T](args: T) -> T:
    ...

@overload
def dprint[*Tp](*args: *Tp) -> tuple[*Tp]:
    ...

def only_once[T,**P](func: Callable[P, T]) -> Callable[P, T]:
    ...

def timeof[T,**P](func: Callable[P, T]) -> Callable[P, T]:
    ...
